### ISSUE TITLE
JavaScript error on call

### ISSUE THREAD

**Issue by djsunrise19** [paviro/MMM-FRITZ-Box-Callmonitor#1]
Hi,

ich habe gestern die neue Version des MM's inkl. der Module ein bisschen getestet. Die Installation und das Starten funktioniert. Leider erhalte ich bei einem Anruf folgenden Error:

![img_2658](https://cloud.githubusercontent.com/assets/14234570/14468213/ff0884de-00de-11e6-8ee5-b589b7d098d9.JPG)

Was kann das sein?

Viele Grüße
Maurice

**EDITED by paviro:** Translated title into English.

**Comment by paviro** [comment]
Ich beantworte das mal in Englisch, da anscheinend nicht nur in Deutschland die Fritz!Box verbreitet ist.

Well this should be an easy fix, I will look into it this evening and let you know what I can find!

**Comment by djsunrise19** [comment]
Macht Sinn ;).

Thank you!

**Comment by paviro** [comment]
Are you sure you have the `addressbook.js` file in your MMM-FRITZ-Box-Callmonitor-module folder? Try redownloading anything I can't reproduce your error...

**Comment by djsunrise19** [comment]
Yes, the file is there. But I've found the problem. I copied the old `addressbook.js` file. There you work with `obj` and not with `a_obj`. I changed that, now it works.

**Comment by paviro** [comment]
Ah I see, will change that anyway someday if I find a better way...
Glad it works if you have any further questions or any suggestions for future updates let me know!
