### ISSUE TITLE
Error: Cannot find module 'vcard-json'�[0m

### ISSUE THREAD

**Issue by djsunrise19** [paviro/MMM-FRITZ-Box-Callmonitor#10]
Hi,

since the lateset `get pull` from MM² yesterday, the software doesn't start anymore. `nohup.out` has the following error. When I deactivate the call monitor, everything works fine:

`Error: Cannot find module 'vcard-json'�[0m`

Perhaps you can have a look at it. 

Thanks,
Maurice

**Comment by paviro** [comment]
Enter the module directory and execute "npm install" :)

**Comment by djsunrise19** [comment]
I've done this. And till yesterday everything works fine.

**Comment by paviro** [comment]
Did you update the module too or change anything related to the module?

**Comment by djsunrise19** [comment]
I made a `git pull` for the MM² and all of my modules. Everything is up-to-date.

**Comment by paviro** [comment]
Can you enter the `node_modules` folder inside of my module an see if there is a `vcard-json` folder?

**Comment by djsunrise19** [comment]
Yes, it is. If I add my vcf to the config file, the mirror starts... Weird. Vcard is optional, isn't it?

**Comment by paviro** [comment]
Yes it is, can you show me your config entry?

**Comment by djsunrise19** [comment]
Sure:

![fcall](https://cloud.githubusercontent.com/assets/14234570/15039972/41430df4-12b1-11e6-876b-bf5ecc4e879b.jpg)

**Comment by paviro** [comment]
Have you checked your web inspector? Are there any errors there? I just removed the vCard in my setup and it works without problems :/

**Comment by djsunrise19** [comment]
I removed the vcard entry again and it works now, embarassing :-D. I think I forgot to add the fritzIP. But I don't understand the error message `vcard`... Mh. Whatever, thank you ;).

**Comment by djsunrise19** [comment]
Can I ask you another question? Which OS do you use. Perhaps you've read that I have performance and heat issues. And I don't know why. With wheezy everything was fine. Since jessie I had this problem with MM1 and MM2.

**Comment by paviro** [comment]
Raspbian and OSX for development. Glad it works! :)

**Comment by djsunrise19** [comment]
Do I have a chance to get the MM² working with another OS? Since months I have no idea what my problem is.

**Comment by paviro** [comment]
Sure you should be able to use any os.

**Comment by djsunrise19** [comment]
any recommendations?

**Comment by paviro** [comment]
No really :D sorry..
