### ISSUE TITLE
Make use of TR-064 API

### ISSUE THREAD

**Issue by Jopyth** [paviro/MMM-FRITZ-Box-Callmonitor#11]
I am currently working on exploring the possibilities of the TR-064 API. It can be used to access Fritz.Box settings / phone books / call list. Do you think this makes sense? Depending on how far I get, I will fork the project and upload my progress. Currently when I come home and start the mirror, any calls I missed while away will not be displayed, since the mirror did not record them. Also the phone book management as a vcard file does not work for me, my contacts are in the Fritz.Box only at the moment.

There is a [node library](https://github.com/hendrikw01/tr-064) which implements the protocol, and a (little bit outdated) [documentation](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/X_contactSCPD.pdf)

The correct naming of the services can be read from the device:
```javascript
const tr = require("tr-064");

var tr064 = new tr.TR064();
tr064.initTR064Device("fritz.box", 49000, function (err, device) {
    if (!err) {
        console.log("=== " + device.meta.friendlyName + " ===");
        device.meta.servicesInfo.forEach(function (serviceType) {
            var service = device.services[serviceType];
            console.log("  ---> " + service.meta.serviceType + " <---");
            service.meta.actionsInfo.forEach(function (action) {
                console.log("   # " + action.name + "()");
                action.inArgs.forEach(function (arg) {
                    console.log("     IN : " + arg);
                });
                action.outArgs.forEach(function (arg) {
                    console.log("     OUT: " + arg);
                });
            });
        });
    }
});
```

**Comment by paviro** [comment]
Hey there, sorry for the delayed answer. It would be awesome if you could add this to the module and also replace the current way missed calls are handled! :)
