### ISSUE TITLE
vCard einbinden

### ISSUE THREAD

**Issue by dasepp89** [paviro/MMM-FRITZ-Box-Callmonitor#13]
Hi,

I need help.
My mirror shows me only the number if someone calls me.
But I would like to see the Name.

Den Rest jetzt auf Deutsch:
Zum einen ist mir nicht ganz klar, wie aus meinem Telefonbuch von der FritzBox eine vcf erzeugen kann.
Zum anderen kenne ich es so, dass Pro Kontakt eine vcf erzeugt wird. Aber ich werde doch keine 350 vcfs einbinden müssen, oder?

Bestimmt stell ich mich grad nur wieder blöd an. Eine kleine Hilfestellung wäre total super :-)

Grüße

**Comment by paviro** [comment]
Hi there,
A vCard can hold multiple contacts. My contact app on  macOS for example exports multiple contacts as one file. Please use google to find out how to do it with yours :)

**Comment by Jopyth** [comment]
You can wait for pull request #14 or check out my fork: https://github.com/Jopyth/MMM-FRITZ-Box-Callmonitor 

Bei mir klappt es wenn ich die Nummern in das 0123 4567891 Format im Fritz!Box Addressbuch ändere (also +49 durch 0 ersetzen und `-` und `/` entfernen.

**Comment by paviro** [comment]
Was klappt? Ich meine bei mir ging +49 als packst du die Nummern aus der Box auch durch einen formatter in deiner pullrequest?

**Comment by Jopyth** [comment]
Ja, gerade nutze ich den gleichen. Manchmal hat er das auch richtig gemacht, aber nicht bei allen Nummern.

**Comment by Jopyth** [comment]
Hast du mal reingeschaut was von Nummern übrig bleibt nach dem Formatting? Bei waren dann halt solche Sachen wie:
0123 456789 (6 Ziffern nach der Vorwahl) -> 0123 456789
0123 4567891 (7 Ziffern nach der Vorwahl) -> 23456789

Geht aber natürlich trotzdem solange beide Nummern "gleich" normalisiert werden.

**Comment by paviro** [comment]
Hab ist zum Teil etwas Strange :D aber alles klar danke!

**Comment by dasepp89** [comment]
Servus,

sorry für die späte Antwort... Aber ich habs nach folgender Anleitung geschafft:
http://www.heber.it/?p=1303

vielleicht hilft es dem ein oder anderen.

Danke Paviro und alle anderen ;-)

Grüße
