### ISSUE TITLE
TR-064 API continued

### ISSUE THREAD

**Issue by Jopyth** [paviro/MMM-FRITZ-Box-Callmonitor#17]
Currently there is the issue, that if the Fritz API is used to load recent calls + phonebook, it breaks after a certain number of uses, due to an internal problem of the library used to access the API. I will prepare a PR to solve this issue.

Also I suggest a small (optional) status icon, which shows how many contacts are loaded, or if some error happened.

**Comment by paviro** [comment]
Thanks!

**Comment by paviro** [comment]
Idee? https://forum.magicmirror.builders/topic/657/mmm-fritz-box-callmonitor

**Comment by paviro** [comment]
And one more :D https://forum.magicmirror.builders/topic/713/mmm-fritz-box-callmonitor

**Comment by Jopyth** [comment]
Das recht Fritz!Box Einstellungen zu lesen und zu bearbeiten (der erste Punkt im Screenshot) muss aktiviert sein. Ich kann morgen auch selber antworten. Dann sollte es hoffentlich gehen. 

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Paul-Vincent Roll <notifications@github.com> </div><div>Datum:27.09.2016  23:03  (GMT+01:00) </div><div>An: paviro/MMM-FRITZ-Box-Callmonitor <MMM-FRITZ-Box-Callmonitor@noreply.github.com> </div><div>Cc: Jopyth <joseph@visitare.de>, State change <state_change@noreply.github.com> </div><div>Betreff: Re: [paviro/MMM-FRITZ-Box-Callmonitor] TR-064 API continued (#17) </div><div>
</div>Idee? https://forum.magicmirror.builders/topic/657/mmm-fritz-box-callmonitor

**Comment by Jopyth** [comment]
Unfortunately I can not reproduce the second error. Just created a secondary fresh install of MM, and it worked fine with the following config:
```
git clone git@github.com:MichMich/MagicMirror.git MagicMirror
cd MagicMirror
npm install
cd modules
git clone git@github.com:paviro/MMM-FRITZ-Box-Callmonitor.git
cd config
cp config.js.sample config.js
# edit config here, for example with nano
nano config.js
# finish installation
cd ..
cd modules/MMM-FRITZ-Box-Callmonitor
npm install
cd ../..
node serveronly
```

Added this to my config:
```
	    {
	        module: 'MMM-FRITZ-Box-Callmonitor',
	        position: 'top_right',
	        header: "Calls",
	        config: {
				username: "XXX",
				password: "XXX"
	        }
	    },
```
