### ISSUE TITLE
Example config.js

### ISSUE THREAD

**Issue by Robiv8** [paviro/MMM-FRITZ-Box-Callmonitor#2]
Hallo Paviro,
Can you give me an example config.js to show how and where i put the Fritz Code into.
Thanks

**Comment by paviro** [comment]
Guess what I just did :D
But I am working on some other changes so keep an eye on this repo!

**Comment by Robiv8** [comment]
Great! Thank you.

**Comment by paviro** [comment]
You are welcome!

**Comment by ruedigerott** [comment]
Hello pavio,
is it possible to send me an example for the modules part " config.js? "

kr
Rüdiger

**Comment by paviro** [comment]
Read the README? https://github.com/paviro/MMM-FRITZ-Box-Callmonitor/blob/master/README.md
