### ISSUE TITLE
KeyError: 'NewPhonebookList'

### ISSUE THREAD

**Issue by matthes0815** [paviro/MMM-FRITZ-Box-Callmonitor#23]
Hey,

I just installed your module and it doesn't work, it displays "unknown error". These are the logged lines:

MMM-FRITZ-Box-Callmonitor error while accessing FRITZ!Box:
Traceback (most recent call last):
  File "/home/pi/MagicMirror/modules/MMM-FRITZ-Box-Callmonitor/fritz_access.py", line 74, in <module>
    main(args)
  File "/home/pi/MagicMirror/modules/MMM-FRITZ-Box-Callmonitor/fritz_access.py", line 60, in main
    handle.download_phone_book()
  File "/home/pi/MagicMirror/modules/MMM-FRITZ-Box-Callmonitor/fritz_access.py", line 23, in download_phone_book
    for phonebook_id in result["NewPhonebookList"]:
KeyError: 'NewPhonebookList'

Regards
Matthias

**Comment by Jopyth** [comment]
Hi Matthias,

I am not sure what causes this. What FRITZ!Box do you have and do you know which FRITZ!OS is running on that? Can you execute this on the command line (with or without user name depending on whether you have a user name setup) and post the contents of `api.log` here?

```bash
python -c "import fritzconnection as fc; fc.print_api(password='password')" > api.log
python -c "import fritzconnection as fc; fc.print_api(password='password',user='username')" > api.log
```

Best regards
Joseph

**Comment by matthes0815** [comment]
Hey Joseph,

thank you for your answer. I'm using a 7490 with Fritz!OS 6.60. api.log attached as api.txt
[api.txt](https://github.com/paviro/MMM-FRITZ-Box-Callmonitor/files/560592/api.txt)

Regards
Matthias

**Comment by Jopyth** [comment]
This is exactly the same model, OS version and API as I have, which is bad, because I can not reproduce your error. Do you have any entries in your phonebook? Do you get this error if you execute the python script directly?
`python fritz_access.py -p PASSWORD -u USER`

If so, can you add a `        print result` after [line 22](https://github.com/paviro/MMM-FRITZ-Box-Callmonitor/blob/master/fritz_access.py#L22) of the script and see what the output looks like?

**Comment by matthes0815** [comment]
Yes, there are about 30 entries in the phonebook. Executing the script directly leads to the same error, the print returns
`{}`
followed by the error message
`Traceback (most recent call last):
  File "fritz_access.py", line 75, in <module>
    main(args)
  File "fritz_access.py", line 61, in main
    handle.download_phone_book()
  File "fritz_access.py", line 24, in download_phone_book
    for phonebook_id in result["NewPhonebookList"]:
KeyError: 'NewPhonebookList'`

**Comment by Jopyth** [comment]
I have been able to reach the error you describe, if I use a user without the rights to access the Phonebooks. Please make sure your user has the right to access FRITZ!Box settings.

![Settings](https://forum.magicmirror.builders/uploads/files/1475047655886-settings.png)

**Comment by matthes0815** [comment]
oh damn... I checked the box but unchecked "Smart Home" and didn't notice that this removes the tick from the first box as well. I'm sorry for wasting your time! Thanks for your help!

**Comment by Jopyth** [comment]
No problem, glad it works now!
