### ISSUE TITLE
TR-064 API

### ISSUE THREAD

**Issue by CGabo** [paviro/MMM-FRITZ-Box-Callmonitor#25]
Access the FRITZ!Box contacts via the TR-064 API doesn’t work anymore with the firmware FRITZ!OS: 6.5 or 6.52. -> Copy the .vcf contacts file to the Raspi.

Test with OS 6.52:
Call http://fritz.box:49000/tr64desc.xml   -> ok
Call http://fritz.box:49000/igddesc.xml    -> nok
This link is needed for the query.  AVM took the functionally away, but probably will bring it back, if more people request it. Just open a case ( https://en.avm.de/service ) if you need this function.

**Comment by Jopyth** [comment]
I have version 6.60 installed, and it (still/again) works for me. Is there a newer version? Can you update and see if this enables the API again?

**Comment by CGabo** [comment]
Yes, you're right, but the International Version with Annex A for CH and A is still on 6.52, same for the English Version.  ;-(
ftp://ftp.avm.de/fritz.box/fritzbox.7490/firmware/
The 6.6 will be released later.  I will update it as soon as it is available.
Thanks

**Comment by Jopyth** [comment]
Well, that sucks.

**Comment by paviro** [comment]
So we just have to wait? I will close this for now, feel free to reopen!
