### ISSUE TITLE
How to read the phonenumbers

### ISSUE THREAD

**Issue by chrisvanlaar** [paviro/MMM-FRITZ-Box-Callmonitor#26]
On the mirror i see the both modules ( recent call and actual call) but how and where i must setup it so that i can see the name from the caller (i only see the number) and it don't show the recent calls (it say continue, no recent call)

The (API?) code in the readme file where paste i this? (i want to read the phonebook in my fritzbox only)
It is not clear for me how to make this work.

Thanks Chris

**Comment by Jopyth** [comment]
Do you still have problems? Please check out this [topic in the forum](https://forum.magicmirror.builders/topic/657/mmm-fritz-box-callmonitor/26). Also lets continue the discussion there.
