### ISSUE TITLE
JS TypeError

### ISSUE THREAD

**Issue by tomppasalmi** [paviro/MMM-FRITZ-Box-Callmonitor#3]
Thanks for the great module,

I have error in MMM-FRITZ-Box-Callmonitor.js when call is coming and in hangup.

LIne 24 and 31. 
"TypeError: self.sendNotification is not a function. (In 'self.sendNotification', 'self.sendNotification' is undefined)"

"TypeError: self.sendNotification is not a function. (In 'self.sendNotification("HIDE_ALERT")', 'self.sendNotification' is undefined)"

Mayby there is something I did wrong?

**Comment by paviro** [comment]
Hi @tomppasalmi,
I will look into it.

Cheers,
Paul

**Comment by paviro** [comment]
Should be fixed now, no idea why it worked on my mirror in the first place shouldn't have...

**Comment by paviro** [comment]
Found out why it worked for me... Had a test module running which declared self as this globally...
But still no idea why I used self there, probably copy and pasted from my other module where I really use self..

**Comment by tomppasalmi** [comment]
Thanks,

Now it is working.

**Comment by paviro** [comment]
Great! I hope it is useful to you 😊 If you have any further questions or feature requests, don't hesitate to ask.

**Comment by Sammydk1984** [comment]
Wird es auch eine version ohne Cam geben?

**Comment by paviro** [comment]
Ohne Cam?

**Comment by Sammydk1984** [comment]
Ich versuche die ganze Zeit MMM-FRITZ-Box-Callmonitor zum laufen zu bringen nur wenn ich das 
{
    module: 'MMM-Facial-Recognition',
    config: {
        //Font size of the phonenumber displayed in the alert
        NumberFontSize: "30px",
        //IP Adress of your FRITZ!Box
        fritzIP: '192.168.178.1',
        //Port of your FRITZ!Box (you should not have to change that)
        fritzPort: 1012
    }
}
In der config Einträge bleibt der Bildschirm schwarz.. 

Kann das sein das das daran liegt weil ich keine Kamera am Pi habe?

**Comment by paviro** [comment]
Dieses Modul benötigt keine Kamera. Anscheinend hast du einen Fehler in deiner Config-Datei, schau mal in den Web Inspektor, der Fehler sollte dort angezeigt werden. Du kannst auch deine ganze config.js hochladen, dann schaue ich sie mir an.

**Comment by Sammydk1984** [comment]
Hir die Daten 

https://www.dropbox.com/sh/leb8hdmx5jsx189/AAC_RRaEHmShIy4QA3SXh6Cga?dl=0

**Comment by paviro** [comment]
Das Module heißt nicht Facialrecognition sondern MMM-FRITZ-Box-Callmonitor.

**Comment by Sammydk1984** [comment]
Steht im github so das man das eintragen soll. Und wenn ich das Modul MMM-FRITZ-Box-Callmonitor Einträge passiert nix.

**Comment by paviro** [comment]
Ich weiß. Fixe ich danke :)
Wie es passiert nichts? Es soll auch nichts passieren, wenn keiner anruft.

**Comment by Sammydk1984** [comment]
Ja selbst wenn ich einen Anruf bekomme geht oder besser zeigt er nix... Hör mal die Änderung 

https://www.dropbox.com/s/ir9zk45m0907o3o/config.js?dl=0

**Comment by Sammydk1984** [comment]
Noch eine Frage hätte ich noch. Wird es eine version geben wo die letzten Anrufe aufgelistet werden.

**Comment by paviro** [comment]
Bitte mache einen neuen "Issue" mit dem Wunsch auf, indem du deinen Funktionswunsch beschreibst, ich antworte dir dann da :)

Zur config: bitte schau in den Web Inspektor der Fehler sollte dort ersichtlich sein.

**Comment by Sammydk1984** [comment]
Also das Modul ist registriert werden auch keine Fehler angezeigt. Kann das sein das das nur für analog geht? Mein Telefon ist über dect angeschlossen.

**Comment by paviro** [comment]
Spielt keine Rolle. Es geht auch, wenn gar kein Telefon angeschlossen ist. Hast du den Callmonitor aktiviert?

**Comment by Sammydk1984** [comment]
Jap habe ich

**Comment by paviro** [comment]
In der Web Konsole gibt es keine Fehler im der Command Line auch nicht?

**Comment by Sammydk1984** [comment]
Bin gerade unterwegs gebe dir später mal die Daten das du dir das bitte mal anschauen kannst. Kann ja sein das ich irgendwo was vergessen habe nur den Wald vor lauter beumen nicht sehe.

**Comment by Sammydk1984** [comment]
Gibt es ne Möglichkeit dir ne Pm oder Email zukomme zu lassen?

**Comment by paviro** [comment]
kontakt@paviro.de <mailto:kontakt@paviro.de>

**Comment by Sammydk1984** [comment]
Hab dir die Daten gesendet

**Comment by paviro** [comment]
Noch nichts angekommen.

**Comment by Sammydk1984** [comment]
Hab es an kontakt@paviro.de gesendet

**Comment by Sammydk1984** [comment]
Paviro sorry das ich nen bissel nerve. Kannst du mir helfen das Wetter Modul für Wetter.de anzupassen.

**Comment by paviro** [comment]
Nein tut mir leid, dass ist nicht, was ich eben machen kann und ich sehe auch keinen Grund. Das momentane Module ist mehr als ausreichend.

**Comment by fischbear** [comment]
Hallo Paviro,

erst einmal vielen Dank für die viele Mühe die du dir gemacht hast. Leider wird mir nach der Installation nichts auf der Oberfläche angezeigt. Die Box ist eine 7490, das MagicMirror das aktuellste. In der config habe ich genau das was du vorgibst. Hast du noch einen heissen tip?
