### ISSUE TITLE
Activate Monitor via relay on incoming call ?

### ISSUE THREAD

**Issue by AWSW-de** [paviro/MMM-FRITZ-Box-Callmonitor#34]
Hello,
first of all thanks for this module. Works fine so far. :)

I am searching for a solution to turn on my monitor on an incoming call. The monitors power is already switched on and off with an relay combined with an PIR sensor with these commands within an .py-script:

ON:
subprocess.call("gpio export 21 out", shell=True)

OFF:
subprocess.call("gpio export 21 in", shell=True)

How can I use these commands to activate the monitor when a call comes in and deactivate it again when the call ends?

Thanks in advance.

Kind Regards :)

**Comment by BoraSchninsky** [comment]
very interesting!!!! any solution for this????

**Comment by AWSW-de** [comment]
Just for info... I solved this in the end by using NODE RED...
