### ISSUE TITLE
Recent calls yes, current calls no

### ISSUE THREAD

**Issue by ifireghost** [paviro/MMM-FRITZ-Box-Callmonitor#38]
Hi guys, after not working with the original code from @paviro (the Pi would just display no previous calls), @armybean 's fork got my installation working again, even showing older entries before MagicMirror was booted. The original code didn't manage to fetch the address book from my 7590, armybean's did. 🙏 However, incoming calls are not being displayed live. This leads me to assume, that my installation is working correct. Also, the 7590's call monitor is active, as "nc fritz.box 1012" shows incoming calls perfectly. Did AVM maybe change something recently that broke the code?

**Comment by ifireghost** [comment]
My config:

module: 'MMM-FRITZ-Box-Callmonitor',
                                position: 'fullscreen', // This can be any of the regions. Best results in left or right regions.
                                header: "Anrufe", // This is optional
                                        config: {
                                                fritzIP: "192.168.13.1",
                                                fritzPort: 1012,
                                                username: "XXX",
                                                password: "XXX",
                                                showContactsStatus: true,
                                                showConnectionStatus: true,
                                                debug: true
                                                }

**Comment by armybean** [comment]
This is my config and showing the overlay for incoming calls:

{
                        module: "MMM-FRITZ-Box-Callmonitor",
                        position: "top_left",   // This can be any of the regions. Best results in left or right regions.
                        header: "Kürzliche Anrufe", // This is optional
                        config: {
                                // See 'Configuration options' for more information.
                                username: "xxx",
                                password: "xxx",
                                showOutgoing: true,
                                colorEnabled: true,
                                maximumCallDistance: 10080, // 7 days
                                maximumCalls: 10,
                                showDuration: true,
                                debug: true
                        }
                },

You should also make sure that the "alert" module is still active. Maybe it is interfering with the "fullscreen" position?

**Comment by ifireghost** [comment]
Actually, the alert module might be off 😬Good hint! I will check, thanks 😊

**Comment by ifireghost** [comment]
YES, that did it!
