### ISSUE TITLE
Call History 

### ISSUE THREAD

**Issue by Sammydk1984** [paviro/MMM-FRITZ-Box-Callmonitor#4]
Kannst du eine version schreiben wo die letzten Anrufe angezeigt werden Name oder Nummer?

**Comment by paviro** [comment]
Habe ich auch schon überlegt, nur würden dann alle angezeigt werden, auch, wenn man dran geht.. Und wann blende ich sie aus? Einfach nach einer gewissen Zeit? Was meinst du?

**Comment by Sammydk1984** [comment]
Also ich würde die letzten 5 anzeigen lassen. Und genau wie beim Kalender ne Tag oder Zeit Angabe dahinter. ZB

**Comment by paviro** [comment]
Added.
